In [2]:
import numpy as np

1. Buatlah Tensor di bawah ini dengan Python:

In [3]:
tensor_1 = np.array([[[[23,50],[7,12]],[[57,67],[99,43]]],[[[75,21],[57,12]],[[87,26],[18,84]]]])
                     
tensor_1

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

In [4]:
tensor_1.shape

(2, 2, 2, 2)

2. Lakukan perkalian terhadap matrix berikut: 

In [5]:
vector_a = np.array([[23, 50 , 19],
                     [7, 12, 109],
                     [57, 67, 98]])
vector_b = np.array([[17],
                     [22],
                     [19]])


vector_a*vector_b


array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

In [6]:
A = np.array([[23, 50 , 19],
              [7, 12, 109],
              [57, 67, 98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [7]:
# Transpose
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [8]:
# Inverse
A_inv = np.linalg.inv(A)
A_inv

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [9]:
# Determinant
np.linalg.det(A)

131344.0000000002