In [1]:
import numpy as np

In [2]:
# buat variable

A = np.array([[1,-1],
              [6, 4]])

A

array([[ 1, -1],
       [ 6,  4]])

In [6]:
# check determinant
np.linalg.det(A)

9.999999999999998

In [3]:
# Check eigenvector
eig_value, eig_vector = np.linalg.eig(A)


In [4]:
eig_vector

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

apakah [[1],[3]] adalah eigenvector nya? salah!!

In [5]:
# eigenvalue
eig_value

array([2.5+1.93649167j, 2.5-1.93649167j])